version: '3.8'

services:
  app:
    image: php:7.4-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=sallesforcedb
      - DB_USERNAME=zombie
      - DB_PASSWORD=g9SHhLek0vJZ12sjVEPTXH6xUf03CsST
    depends_on:
      - db
    command: |
      bash -c "composer install &&
      php artisan migrate --force &&
      php artisan db:seed --force &&
      php artisan serve --host=0.0.0.0 --port=8000"
      
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: sallesforcedb
      POSTGRES_USER: zombie
      POSTGRES_PASSWORD: g9SHhLek0vJZ12sjVEPTXH6xUf03CsST
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
