services:
  - type: web
    name: salles-force
    env: php
    buildCommand: "composer install && php artisan migrate"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
